DROP TABLE IF EXISTS `ast_NameTest_M`;

CREATE TABLE `ast_NameTest_M` ( `tsid` VARCHAR(256) NOT NULL, `sName` VARCHAR(256) NOT NULL, `sNo` INT(10) NOT NULL, `createdBy` VARCHAR(64) NULL DEFAULT '-1', `createdDate` TIMESTAMP NULL DEFAULT '2000-01-01 10:10:10', `updatedBy` VARCHAR(64) NULL DEFAULT '-1', `updatedDate` TIMESTAMP NULL DEFAULT '2000-01-01 10:10:10', `versionId` INT(10) NULL DEFAULT '-1', `activeStatus` INT(1) NULL DEFAULT '1', `txnAccessCode` INT(10) NULL DEFAULT NULL, PRIMARY KEY (`tsid`));

