Ext.define('Testlic1.testlic1.web.com.view.appinsight.health.Newui', {
     "xtype": "newui",
     "items": [{
          "xtype": "textfield",
          "fieldLabel": "TextField",
          "margin": 5,
          "bindable": "t1",
          "name": "t1",
          "itemId": "textfield_ext_5026"
     }, {
          "xtype": "textfield",
          "fieldLabel": "TextField",
          "margin": 5,
          "bindable": "t2",
          "name": "t2",
          "itemId": "textfield_ext_5036"
     }, {
          "xtype": "textfield",
          "fieldLabel": "TextField",
          "margin": 5,
          "bindable": "t3",
          "name": "t3",
          "itemId": "textfield_ext_5048"
     }, {
          "xtype": "textfield",
          "fieldLabel": "TextField",
          "margin": 5,
          "bindable": "t4",
          "name": "t4",
          "itemId": "textfield_ext_5062"
     }, {
          "xtype": "textfield",
          "fieldLabel": "TextField",
          "margin": 5,
          "bindable": "t5",
          "name": "t5",
          "itemId": "textfield_ext_5078"
     }, {
          "xtype": "textfield",
          "fieldLabel": "TextField",
          "margin": 5,
          "bindable": "t6",
          "name": "t6",
          "itemId": "textfield_ext_5096"
     }, {
          "xtype": "textfield",
          "fieldLabel": "TextField",
          "margin": 5,
          "bindable": "t7",
          "name": "t7",
          "itemId": "textfield_ext_5116"
     }, {
          "xtype": "button",
          "name": "b5",
          "text": "Button",
          "margin": 5,
          "itemId": "button_ext_5246",
          "listeners": {
               "click": "onB5Click"
          }
     }, {
          "xtype": "button",
          "name": "b6",
          "text": "Reset",
          "margin": 5,
          "isResetButton": true,
          "itemId": "button_ext_5278",
          "listeners": {
               "click": "onB6Click"
          }
     }],
     "border": true,
     "autoScroll": true,
     "title": "Form",
     "margin": 5,
     "dockedItems": [],
     "itemId": "form_ext_5018",
     "extend": "Ext.form.Panel",
     "requires": ["Testlic1.testlic1.web.com.controller.appinsight.health.NewuiController", "Testlic1.testlic1.shared.com.viewmodel.appinsight.health.NewuiViewModel", "Testlic1.testlic1.shared.com.model.appinsight.health.NewuiModel"],
     "viewModel": "NewuiViewModel",
     "controller": "NewuiController"
});