Ext.define('Testlic1.testlic1.shared.com.model.appinsight.health.NewuiModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "t1",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "t2",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "t3",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "t4",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "t5",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "t6",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "t7",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "b5",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "b6",
          "type": "auto",
          "defaultValue": ""
     }]
});