Ext.define('Newpro.newpro.shared.com.model.appinsight.health.CategoryModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "cid",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "categorynm",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "brandnm",
          "reference": "Brands",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});