Ext.define('Newpro.newpro.shared.com.model.appinsight.health.TestOneModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "ttid",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "tnm",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "tno",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "aaa",
          "reference": "TestA",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});