Ext.define('Newpro.newpro.shared.com.model.appinsight.health.TestAModel', {
     "extend": "Ext.data.Model",
     "fields": [{
          "name": "primaryKey",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "aa",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "anm",
          "type": "string",
          "defaultValue": ""
     }, {
          "name": "ano",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "aDate",
          "type": "auto",
          "defaultValue": ""
     }, {
          "name": "versionId",
          "type": "int",
          "defaultValue": ""
     }, {
          "name": "entityAudit",
          "reference": "EntityAudit"
     }, {
          "name": "primaryDisplay",
          "type": "string",
          "defaultValue": ""
     }]
});