DROP TABLE IF EXISTS `ast_TestA_T`;

CREATE TABLE `ast_TestA_T` ( `aid` VARCHAR(256) NOT NULL, `anm` VARCHAR(256) NOT NULL, `ano` INT(10) NOT NULL, `total` INT(10) NOT NULL, `ano1` INT(10) NOT NULL, `createdBy` VARCHAR(64) NULL DEFAULT '-1', `createdDate` TIMESTAMP NULL DEFAULT '2000-01-01 10:10:10', `updatedBy` VARCHAR(64) NULL DEFAULT '-1', `updatedDate` TIMESTAMP NULL DEFAULT '2000-01-01 10:10:10', `versionId` INT(11) NULL DEFAULT '-1', `activeStatus` INT(1) NULL DEFAULT '1', `txnAccessCode` INT(11) NULL DEFAULT NULL, PRIMARY KEY (`aid`));

